"""
Emit \\input{}-able LaTeX tables and figures from the artifact files.

    ~/.venv/bin/python3 paper/build_tables.py                 # everything available
    ~/.venv/bin/python3 paper/build_tables.py --only overlay  # just the overlay

Every number is read from an artifact (JSON, or taskb's run log); nothing is
retyped here. An emitter whose inputs are missing prints "skipped" and the run
continues, so this can be run now and again when the overlay lands.

Outputs: paper/tables/*.tex (table floats with \\caption and \\label) and
paper/figures/*.pdf. Requires booktabs and graphicx in the document preamble.
"""

import argparse
import json
import os
import re
from datetime import date

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TAB = os.path.join(REPO, "paper", "tables")
FIG = os.path.join(REPO, "paper", "figures")
EXO = ["asian_call_K100", "uo_barrier_call_K100_B110", "lookback_float_call"]
EXO_TEX = {"asian_call_K100": "Asian call ($K=100$)",
           "uo_barrier_call_K100_B110": "Up-and-out call ($K=100$, $B=110$)",
           "lookback_float_call": "Floating-strike lookback"}
HESTON_P = {"asian_call_K100": 1.61319, "uo_barrier_call_K100_B110": 2.05449, "lookback_float_call": 4.43604}
HESTON_Q = {"asian_call_K100": 1.57207, "uo_barrier_call_K100_B110": 1.76547, "lookback_float_call": 4.62501}
LEVELS = ["C0", "C1", "C2", "C3"]
PRIOR_TEX = {"base": "baseline", "retrain1": "retrain 1", "retrain2": "retrain 2",
             "mu25": r"$\mu = 0.25$", "rho02": r"$\rho = -0.2$", "kappa6": r"$\kappa = 6$"}


# --------------------------------------------------------------------------

def load(*path, required=True):
    p = os.path.join(REPO, *path)
    if not os.path.exists(p):
        if required:
            raise FileNotFoundError(p)
        return None
    with open(p) as f:
        return json.load(f)


def esc(s):
    return str(s).replace("_", r"\_").replace("%", r"\%")


def num(x, d=4):
    return "---" if x is None else f"{x:.{d}f}"


def write(name, body, caption, label, note=None, star=False, source=""):
    os.makedirs(TAB, exist_ok=True)
    env = "table*" if star else "table"
    out = [f"% generated by paper/build_tables.py on {date.today()} -- do not edit by hand",
           f"% source: {source}",
           f"\\begin{{{env}}}[t]", r"\centering", r"\small", body.rstrip()]
    if note:
        out.append(r"\par\smallskip{\footnotesize " + note + "}")
    out += [f"\\caption{{{caption}}}", f"\\label{{{label}}}", f"\\end{{{env}}}", ""]
    p = os.path.join(TAB, name)
    with open(p, "w") as f:
        f.write("\n".join(out))
    print(f"  wrote tables/{name}")


def write_figure(stem, caption, label, star=False, height="4.3cm"):
    """Float wrapper for a generated figure, matching the table floats.

    The height cap is the page budget and must not be relaxed. `width=\\textwidth`
    is given alongside it so graphicx scales to whichever binds first: the height
    never exceeds the cap, and the figure never overruns the column.
    """
    os.makedirs(FIG, exist_ok=True)
    env = "figure*" if star else "figure"
    out = [f"% generated by paper/build_tables.py on {date.today()} -- do not edit by hand",
           f"% height cap {height} is the page budget (see paper/OVERLEAF.md)",
           f"\\begin{{{env}}}[t]", r"\centering",
           f"  \\includegraphics[width=\\textwidth,height={height},keepaspectratio]{{figures/{stem}}}",
           f"  \\caption{{{caption}}}", f"  \\label{{{label}}}", f"\\end{{{env}}}", ""]
    with open(os.path.join(FIG, stem + ".tex"), "w") as f:
        f.write("\n".join(out))
    print(f"  wrote figures/{stem}.tex")


def tabular(cols, header, rows, rules=()):
    L = [f"\\begin{{tabular}}{{{cols}}}", r"\toprule", " & ".join(header) + r" \\", r"\midrule"]
    for i, r in enumerate(rows):
        L.append(" & ".join(r) + r" \\")
        if i + 1 in rules:
            L.append(r"\midrule")
    L += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(L)


# --------------------------------------------------------------------------
# Gaussian appendix (tables 6, 7, 9, 10, 13)
# --------------------------------------------------------------------------

def gaussian():
    g = load("artifacts_gauss", "colab_A100", "gauss_appendix.json", required=False)
    if g is None:
        print("  skipped gaussian: artifacts_gauss/colab_A100/gauss_appendix.json missing")
        return
    src = "artifacts_gauss/colab_A100/gauss_appendix.json"
    c, d = g["config"], g["derived"]
    setup = (f"GBM with $\\mu = {c['mu']}$, $r = {c['r']}$, $\\sigma = {c['sigma']}$, $\\Delta t = 1/252$, "
             f"$H = {c['H']}$; $N = {c['N_train']:,}$ training returns; standardised mean shift "
             f"$d = {d['d_std']:+.4f}$\\,sd. {g['n_paths'] if 'n_paths' in g else c['n_paths']:,} paths, "
             f"{esc(g['device_name'])}. No end-of-process mean adjustment; de-standardisation "
             f"$Y = s_0 z + m_P$ applied once.")

    rows = []
    for k in ("No shift", "Exact SMT", "Estimated SMT", "Retrained Q"):
        t = g["table6"].get(k)
        if not t:
            continue
        bias = t["bias_sd_vs_mP"] if k == "No shift" else t["bias_sd_vs_mQ"]
        rows.append([k, f"{bias:+.4f}", num(t["mart_dev"]), num(t["rmse"]), num(t["mae"]), num(t["W1"]), num(t["KS"])])
    write("gauss_table6.tex",
          tabular("lcccccc", ["Method", "bias (sd)", r"Mart.\ dev.\ $\downarrow$", r"RMSE $\downarrow$",
                              r"MAE $\downarrow$", r"$W_1$ $\downarrow$", r"KS $\downarrow$"], rows),
          "Gaussian (GBM) results. Martingale deviation is $\\max_h |\\mathbb{E}[e^{-rh\\Delta t}S_h] - S_0|$; "
          "RMSE and MAE are against Black--Scholes over $K \\in \\{80,\\dots,120\\}$; $W_1$ and KS compare $S_{21}$ "
          "with a lognormal-$Q$ sample. ``bias'' is the sampled mean return minus each row's own target, in units of "
          "the return standard deviation.", "tab:gauss_full", note=setup, source=src)

    rows = [[f"${float(k):+.2f}$", num(v["mart_dev"]), num(v["rmse"]), num(v["W1"]), f"{v['n']:,}"]
            for k, v in sorted(g["table7"].items(), key=lambda kv: float(kv[0]))]
    write("gauss_table7_lambda.tex",
          tabular("lcccc", [r"$\lambda$", r"Mart.\ dev.\ $\downarrow$", r"RMSE $\downarrow$", r"$W_1$ $\downarrow$", "paths"], rows),
          r"Correction strength $\lambda$: $r_{\mathrm{used}} = \mu + \lambda(r-\mu)$, so $\lambda = 1$ is the exact "
          r"correction and $\lambda = 0$ no correction. The $\lambda = 0$ and $\lambda = 1$ rows are the "
          r"no-shift and exact-SMT draws of Table~\ref{tab:gauss_full} themselves, not repeat runs.",
          "tab:gauss_lambda", source=src)

    names = [n for n in ("No shift", "Exact SMT", "Estimated SMT", "Retrained Q") if n in g["table9"]]
    rows = []
    for H in c["maturities"]:
        r = [str(H)]
        for n in names:
            e = g["table9"][n][str(H)]
            r.append(f"{e['atm']:.3f} ({abs(e['atm'] - e['bs']):.3f})")
        rows.append(r + [f"{g['table9'][names[0]][str(H)]['bs']:.3f}"])
    write("gauss_table9_maturity.tex",
          tabular("l" + "c" * (len(names) + 1), ["$H$ (days)"] + names + ["Black--Scholes"], rows),
          "At-the-money call price against maturity; absolute error against Black--Scholes in parentheses.",
          "tab:gauss_maturity", source=src)

    rows = []
    for k in ("No shift", "Exact SMT", "Estimated SMT", "Retrained Q"):
        t = g["table10"].get(k)
        if t:
            rows.append([k, num(t["E_ST"], 2), num(t["sd_ST"], 2), num(t["KS"]), num(t["E_disc"], 2)])
    any_t = next(iter(g["table10"].values()), None)
    if any_t:
        rows.append([r"Theory $Q$", num(any_t["mean_theory"], 2), num(any_t["sd_theory"], 2), "0", "100.00"])
    write("gauss_table10_terminal.tex",
          tabular("lcccc", ["Method", r"$\mathbb{E}[S_T]$", r"$\mathrm{sd}(S_T)$", "KS vs theory",
                            r"$\mathbb{E}[e^{-rT}S_T]$"], rows),
          r"Terminal price distribution at $H = 21$.", "tab:gauss_terminal", source=src)

    t = g.get("table13")
    if t and "SMT" in t:
        rows = [[k, num(t[k]["mean"][0], 3), num(t[k]["mean"][1], 3), num(t[k]["std"][0], 3), num(t[k]["std"][1], 3)]
                for k in ("No shift", "SMT", "Q_ref", "target") if k in t]
        rows = [[esc(r[0]).replace("Q\\_ref", "$Q$ sample").replace("target", "target $Q$")] + r[1:] for r in rows]
        sh = t["target"]["mean"]
        note = (f"The requested displacement is ${sh[0]/t['target']['std'][0]:.0f}\\sigma$ and "
                f"${sh[1]/t['target']['std'][1]:.0f}\\sigma$. SMT reaches "
                f"{t['SMT']['mean'][0]/sh[0]*100:.0f}\\% and {t['SMT']['mean'][1]/sh[1]*100:.0f}\\% of it, with "
                f"standard deviations at {t['SMT']['std'][0]/t['target']['std'][0]*100:.0f}\\% and "
                f"{t['SMT']['std'][1]/t['target']['std'][1]*100:.0f}\\% of target: the finite-network "
                "extrapolation limit, reported rather than corrected.")
        write("gauss_table13_2d.tex",
              tabular("lcccc", ["", "mean $x_1$", "mean $x_2$", "sd $x_1$", "sd $x_2$"], rows),
              "Two-dimensional Gaussian transport.", "tab:gauss_2d", note=note, source=src)


# --------------------------------------------------------------------------
# Task B (parsed from its run log -- the artifact that run produced)
# --------------------------------------------------------------------------

def taskb():
    p = os.path.join(REPO, "taskb", "full_run.log")
    if not os.path.exists(p):
        print("  skipped taskb: taskb/full_run.log missing")
        return
    txt = open(p).read()
    src = "taskb/full_run.log"
    rows = []
    for line in txt.splitlines():
        m = re.match(r"^(P|C[0-3]|Qflr)\s+(\S+)\s+(\S+)\s+(\S+)\s+([\d,]+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s*$", line)
        if m:
            g = list(m.groups())
            lab = {"P": r"$P$ (Heston)", "Qflr": r"$Q$ noise floor"}.get(g[0], g[0])
            rows.append([lab, g[1], g[2], g[3], g[5], g[6], g[8], g[12], g[13]])
    if not rows:
        print("  skipped taskb: could not parse the summary table")
        return
    write("taskb_sweep.tex",
          tabular("lcccccccc", ["level", "$m$", "screen", "ESS \\%", r"max $w$", r"$\|\beta\|$", "KL",
                                "held-out mart.", "held-out van."], rows),
          r"Task B: entropy projection on raw Heston paths, $N = 10^5$. ESS is the effective sample size of the "
          r"projected weights; the last two columns are held-out diagnostics never used in calibration. "
          r"``$Q$ noise floor'' evaluates the same diagnostics on an independent Heston-$Q$ sample of the same size.",
          "tab:taskb_sweep", source=src)

    block = txt.split("EXOTIC PRICES ACROSS CONSTRAINT LEVELS")[-1].splitlines()
    rows, cur = [], None
    for line in block:
        m = re.match(r"^(\w+)\s+((?:[\d.]+\s+){5}[\d.]+)\s*$", line)
        if m and m.group(1) in EXO:
            cur = [EXO_TEX[m.group(1)]] + m.group(2).split()
        elif cur and line.strip().startswith("(se)"):
            se = line.split()[1:]
            rows.append([cur[0]] + [f"{float(v):.4f} ({float(s):.4f})" for v, s in zip(cur[1:], se)])
            cur = None
    if rows:
        write("taskb_exotics.tex",
              tabular("lcccccc", ["exotic", "Heston-$P$"] + LEVELS + ["Heston-$Q$"], rows),
              r"Task B exotic prices across constraint levels (standard errors in parentheses). Distance to "
              r"Heston-$Q$ is a diagnostic, not a success condition: finite vanilla constraints do not identify "
              r"the path law.", "tab:taskb_exotics", star=True, source=src)


# --------------------------------------------------------------------------
# Task C: gate, dual sweep, frozen-prior acceptance
# --------------------------------------------------------------------------

def _bound_tex(b):
    """Render a bound string as maths: '<= 2.79 (studentised)' -> '$\\le 2.79$ (studentised)'."""
    b = b.strip()
    m = re.match(r"^<=\s*([\d.]+)(.*)$", b)
    if m:
        return rf"$\le {m.group(1)}$" + esc(m.group(2))
    m = re.match(r"^in \[([-\d.]+),\s*([-\d.]+)\]$", b)
    if m:
        return rf"$\in [{m.group(1)}, {m.group(2)}]$"
    m = re.match(r"^\(<=\s*([\d.]+),\s*(.*)\)$", b)
    if m:
        return rf"($\le {m.group(1)}$, " + esc(m.group(2)) + ")"
    return esc(b)


def gate_rows(g):
    order = ["G1-tail", "G1-mean", "G2a", "G2b", "G2b-old"] + [f"G3:{k}" for k in EXO] + ["G4a", "G4b", "G4c"]
    desc = {"G1-tail": "vanilla column means", "G1-mean": "martingale column means",
            "G2a": "martingale column sds",
            "G2b": "vanilla column sds, studentised",
            "G2b-old": r"\emph{superseded: flat sd-ratio bound}",
            "G4a": "realised-variance dispersion", "G4b": "volatility clustering",
            "G4c": "leverage correlation"}
    for k in EXO:
        desc[f"G3:{k}"] = EXO_TEX[k]
    out = []
    for k in order:
        if k not in g:
            continue
        v = g[k]
        mark = r"\checkmark" if v["passed"] else r"$\times$"
        if k == "G2b-old":
            mark = r"\emph{not gated}"
        out.append([esc(k), desc.get(k, ""), num(v["value"]), _bound_tex(v["bound"]), mark])
    return out


def taskc():
    # the re-gate under the amended G2b (section 20) is authoritative; fall back only if absent
    src_gate = "artifacts_taskc/lrema/gate_report_g2bz.json"
    g = load("artifacts_taskc", "lrema", "gate_report_g2bz.json", required=False)
    if g is None:
        g = load("artifacts_taskc", "lrema", "gate_report.json", required=False)
        src_gate = "artifacts_taskc/lrema/gate_report.json (PRE-AMENDMENT)"
        if g is not None:
            print("  WARNING: re-gate artifact missing; the gate table reports the superseded G2b")
    if g:
        amended = "G2b-old" in g
        note = (r"G2b is the studentised criterion adopted after a null study: "
                r"$\max_j |\hat{s}_{A,j}/\hat{s}_{\mathrm{ref},j} - 1| / \sigma_j$ with "
                r"$\sigma_j = \sqrt{(\kappa_j-1)/4 \cdot (1/n_A + 1/n_{\mathrm{ref}})}$ measured on the reference "
                r"sample. The row below it is the superseded flat bound, reported for continuity and not gated; "
                r"it fails 27\% of pairs drawn from the same law at this sample size." if amended else
                r"G2b is the original flat sd-ratio bound (superseded; see the appendix).")
        write("taskc_gate.tex",
              tabular("llccc", ["check", "statistic", "value", "bound", "pass"], gate_rows(g)),
              r"Pre-registered acceptance gate for the learned path prior $P_\theta$, evaluated against an "
              r"independent sample of its own simulator ($10^5$ paths each). Thresholds were fixed before the "
              r"model was trained; the one amendment is recorded in the appendix. G3 entries are in units of the "
              r"combined standard error.",
              "tab:taskc_gate", note=note, source=src_gate)
        # alias: the manuscript inputs this table as tables/app_gate
        import shutil
        shutil.copyfile(os.path.join(TAB, "taskc_gate.tex"), os.path.join(TAB, "app_gate.tex"))
        print("  wrote tables/app_gate.tex (alias of taskc_gate.tex)")

    s = load("artifacts_taskc", "lrema", "sweep", "sweep.json", required=False)
    if s:
        rows = []
        for lvl in LEVELS:
            L = s["levels"][lvl]
            rows.append([lvl, str(L["m"]), num(L["screen_margin"], 3), esc(L["screen_bite"]),
                         num(L["beta_raw_norm"], 2), f"{L['ess_C']*100:.2f}", num(L["kl"], 4),
                         num(L["ho_van_in"]), num(L["ho_van_C"])])
        write("taskc_dual.tex",
              tabular("lccccccc c", ["level", "$m$", "screen margin", "first bite", r"$\|\beta_{\mathrm{raw}}\|$",
                                     "ESS \\%", "KL", "held-out van.\\ (in)", "held-out van.\\ (cross)"], rows),
              r"Entropy projection against the learned prior $P_\theta$: dual solved on $10^6$ generated paths, "
              r"every reported quantity evaluated on an independent $10^5$-path sample. The screen margin is in "
              r"units of the raw column standard deviation; $\beta_{\mathrm{raw}}$ is reported in raw units so it "
              r"is comparable across sources.", "tab:taskc_dual", star=True,
              source="artifacts_taskc/lrema/sweep/sweep.json")

        rows = []
        for k in EXO:
            u = s["unweighted_C"]["exotics"][k]
            r = [EXO_TEX[k], f"{u[0]:.4f} ({u[1]:.4f})"]
            for lvl in LEVELS:
                e = s["levels"][lvl]["exotics_C"][k]
                r.append(f"{e[0]:.4f} ({e[1]:.4f})")
            span = HESTON_P[k] - HESTON_Q[k]          # signed: "closed" is a fraction of the P->Q move
            closed = (HESTON_P[k] - s["levels"]["C3"]["exotics_C"][k][0]) / span * 100
            rows.append(r + [f"{HESTON_Q[k]:.4f}", f"{closed:+.0f}\\%"])
        write("taskc_exotics.tex",
              tabular("lccccccc", ["exotic", r"$P_\theta$"] + LEVELS + ["Heston-$Q$", "span closed"], rows),
              r"Exotic prices under the projected measure with the learned prior as source (standard errors in "
              r"parentheses). ``Span closed'' is the fraction of the Heston $P \to Q$ distance covered at C3.",
              "tab:taskc_exotics", star=True, source="artifacts_taskc/lrema/sweep/sweep.json")

    # frozen-prior acceptance: every prior that has a gate report
    rows = []
    for tag in ("lrema", "retrain1", "retrain2", "mu25", "rho02", "kappa6"):
        g = load("artifacts_taskc", tag, "gate_report.json", required=False)
        if not g:
            continue
        fails = [k for k, v in g.items() if isinstance(v, dict) and "passed" in v and not v["passed"] and k != "G1-info"]
        worst = max((v["value"] / float(v["bound"].replace("<=", "").strip())
                     for k, v in g.items() if isinstance(v, dict) and "bound" in v and "<=" in v["bound"]), default=float("nan"))
        rows.append([PRIOR_TEX.get("base" if tag == "lrema" else tag, esc(tag)),
                     r"\checkmark" if g.get("passed") else r"$\times$",
                     f"{worst*100:.0f}\\%",
                     ", ".join(esc(f) for f in fails) if fails else "---",
                     f"{g.get('n_A', 0):,}"])
    if rows:
        write("taskc_prior_acceptance.tex",
              tabular("lcccc", ["prior", "accepted", "tightest check", "failed checks", "paths"], rows),
              r"Acceptance of each candidate prior against its own simulator under the pre-registered gate. "
              r"``Tightest check'' is the largest value as a percentage of its bound across the one-sided checks. "
              r"A prior that fails twice is dropped from the overlay and reported here rather than omitted.",
              "tab:prior_acceptance", source="artifacts_taskc/*/gate_report.json")


# --------------------------------------------------------------------------
# Amortization
# --------------------------------------------------------------------------

def amortization():
    a = load("artifacts_taskc", "lrema", "amort74_colab", "amortization.json", required=False)
    if a is None:
        print("  skipped amortization: artifacts_taskc/lrema/amort74_colab/amortization.json missing")
        return
    src = "artifacts_taskc/lrema/amort74_colab/amortization.json"
    st = a["stages"]
    b, arms = st["budget"], st["arms"]
    w, A = b["armW"], b["armA"]
    rows = [["weighted (importance sampling)", f"{w['n_paths']:,}", f"{w['net_evals']/1e9:.2f}", f"{w['seconds']:.0f}"],
            ["amortised sampler", f"{A['n_paths']:,}", f"{A['net_evals']/1e9:.2f}", f"{A['seconds']:.0f}"],
            [r"\emph{ratio}", f"{w['n_paths']/A['n_paths']:.1f}", f"{w['net_evals']/A['net_evals']:.1f}", f"{w['seconds']/A['seconds']:.1f}"]]
    ess = arms["ess_C"] * 100
    write("amort_compute.tex",
          tabular("lccc", ["arm", "paths", r"network evaluations ($10^9$)", "wall-clock (s)"], rows, rules=(2,)),
          r"Compute for the two representations of the same projected measure, on one device. The weighted arm "
          r"must draw the $10^6$-path sample the dual is solved on; the amortised arm pays that once and then "
          r"samples directly, and its cost includes training $h_\psi$.",
          "tab:amort_compute",
          note=(f"Effective sample size of the weights at the full constraint set: {ess:.2f}\\%, so weighting "
                f"discards only {100-ess:.1f}\\% of paths --- the cost difference is not an ESS effect. Charged "
                r"with the solve draw as a shared fixed cost, the marginal cost of $10^5$ unweighted paths "
                r"favours the weighted arm; the amortised arm wins when fresh paths are drawn repeatedly."),
          source=src)

    rows = []
    for k in EXO:
        v = arms["exotics"][k]
        sm, ss = v["smt"]; wm, ws = v["weighted"]
        rows.append([EXO_TEX[k], f"{sm:.4f} ({ss:.4f})", f"{wm:.4f} ({ws:.4f})",
                     f"{sm-wm:+.4f}", f"{(sm-wm)/ (ss**2+ws**2)**0.5:+.2f}", f"{ws/ss:.2f}"])
    c, h = arms["calibrated"], arms["heldout"]
    note = (f"Constraint columns: calibrated ({c['m']}) agree to {c['smt_vs_w_max']:.2f} standard errors, "
            f"{c['smt_vs_w_within2']}/{c['m']} within two; held out ({h['m']}) to {h['max']:.2f}, "
            f"{h['within2']}/{h['m']} within two. Sliced Wasserstein between the two representations is "
            f"{arms['sw']['test']:.4f} against a null of {arms['sw']['null']:.4f} for two independent draws of the "
            f"prior and a tilt size of {arms['sw']['signal']:.4f}.")
    write("amort_agreement.tex",
          tabular("lccccc", ["exotic", "amortised (SE)", "weighted (SE)", "difference", "in SE", "SE ratio"], rows),
          r"Agreement between the amortised sampler and the weighted representation at the full constraint set. "
          r"No exotic differs by more than two standard errors: the two are the same measure to within Monte "
          r"Carlo error.", "tab:amort_agreement", note=note, star=True, source=src)


# --------------------------------------------------------------------------
# Overlay (runs the moment artifacts_overlay/overlay.json lands)
# --------------------------------------------------------------------------

def _overlay_data():
    """Accept either the notebook's overlay.json (tag -> sweep) or per-prior sweep.json files."""
    for cand in (("artifacts_overlay", "overlay.json"), ("artifacts_taskc", "overlay", "overlay.json")):
        d = load(*cand, required=False)
        if d:
            return d, "/".join(cand)
    out = {}
    for tag in PRIOR_TEX:
        disk = "lrema" if tag == "base" else tag          # the baseline's own run directory
        s = load("artifacts_overlay", tag, "sweep", "sweep.json", required=False) or \
            load("artifacts_taskc", disk, "sweep", "sweep.json", required=False)
        if s:
            out[tag] = s
    return (out, "artifacts_overlay/<prior>/sweep/sweep.json") if out else (None, None)


def overlay():
    data, src = _overlay_data()
    if not data:
        print("  skipped overlay: no overlay.json or per-prior sweep.json yet")
        return
    base = data.get("base") or data.get("lrema")
    if base is None:
        print("  skipped overlay: no baseline prior in the results")
        return
    mis = [t for t in ("mu25", "rho02", "kappa6") if t in data]
    retr = [t for t in ("retrain1", "retrain1b", "retrain2") if t in data]
    if not mis or not retr:
        # an "overlay" without a misspecified prior or without the training-variance
        # band would invite reading seed noise as prior dependence.
        print(f"  skipped overlay: incomplete ({len(data)} priors: {sorted(data)}); "
              "needs the baseline, at least one retrain, and at least one misspecified prior")
        return

    # --- figure: exotic price vs constraint level, one band per prior
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import numpy as np
    os.makedirs(FIG, exist_ok=True)
    fig, ax = plt.subplots(1, 3, figsize=(13.5, 4.2))   # aspect ~3.25 so height 4.3cm fits \textwidth
    x = np.arange(len(LEVELS) + 1)
    for axi, k in zip(ax, EXO):
        for tag, s in data.items():
            v = [s["unweighted_C"]["exotics"][k][0]] + [s["levels"][l]["exotics_C"][k][0] for l in LEVELS]
            e = [s["unweighted_C"]["exotics"][k][1]] + [s["levels"][l]["exotics_C"][k][1] for l in LEVELS]
            style = dict(marker="o", ms=3.5, capsize=2, lw=2.0 if tag in ("base", "lrema") else 1.2,
                         ls="-" if tag in ("base", "lrema") else ("--" if tag.startswith("retrain") else "-."))
            axi.errorbar(x, v, yerr=[2 * t for t in e], label=PRIOR_TEX.get(tag, tag), **style)
        axi.axhline(HESTON_Q[k], c="k", ls=":", lw=1)
        axi.axhline(HESTON_P[k], c="0.5", ls=":", lw=1)
        axi.set_xticks(x); axi.set_xticklabels([r"$P_\theta$"] + LEVELS)
        axi.set_title(EXO_TEX[k], fontsize=9); axi.grid(alpha=0.25)
        axi.set_xlabel("vanilla information")
    ax[0].set_ylabel("price")
    ax[0].legend(fontsize=7, frameon=False)
    fig.tight_layout()
    p = os.path.join(FIG, "overlay_identification.pdf")
    fig.savefig(p, bbox_inches="tight"); plt.close(fig)
    print(f"  wrote figures/{os.path.basename(p)}")
    write_figure("overlay_identification",
                 r"Exotic price against the amount of vanilla information, one line per physical prior; bands "
                 r"are $\pm 2$ standard errors. Dotted lines mark the Heston $P$ (grey) and $Q$ (black) values. "
                 r"The two retrainings of the accepted recipe bound the training-variance band; a prior outside "
                 r"that band differs by more than a refit of the same specification.",
                 "fig:overlay", star=True)

    # --- C3 spread table with the retrain band
    band = {}
    if retr:
        for k in EXO:
            vals = [data[t]["levels"]["C3"]["exotics_C"][k][0] for t in retr + ["base"] if t in data]
            band[k] = max(vals) - min(vals)
    rows = []
    for tag, s in data.items():
        r = [PRIOR_TEX.get(tag, esc(tag))]
        for k in EXO:
            d_ = s["levels"]["C3"]["exotics_C"][k][0] - base["levels"]["C3"]["exotics_C"][k][0]
            se = (s["levels"]["C3"]["exotics_C"][k][1] ** 2 + base["levels"]["C3"]["exotics_C"][k][1] ** 2) ** 0.5
            span = abs(HESTON_P[k] - HESTON_Q[k])          # |P - Q|: the lookback's span is negative
            mark = r"$^{*}$" if (band and tag not in retr + ["base", "lrema"] and abs(d_) > band[k]) else ""
            r.append(f"{d_:+.4f}{mark} ({d_/se:+.1f}, {abs(d_)/span*100:.0f}\\%)")
        r += [f"{s['levels']['C3']['ess_C']*100:.2f}", f"{s['levels']['C0']['beta_raw_norm']:.1f}"]
        rows.append(r)
    note = ""
    if band:
        note = ("Training-variance band at C3 (spread over the baseline and its independent retrains): " +
                ", ".join(f"{EXO_TEX[k]} {band[k]:.4f}" for k in EXO) +
                r". $^{*}$ marks a prior whose spread exceeds that band. The band is built from priors that "
                r"passed the acceptance gate and is therefore narrower than unconditional seed variance.")
    write("overlay_spread.tex",
          tabular("lcccrr", ["prior"] + [EXO_TEX[k] for k in EXO] + ["ESS \\% (C3)", r"$\|\beta_{\mathrm{raw}}\|$ (C0)"], rows),
          r"Exotic price at the fullest constraint level, as a difference from the baseline prior "
          r"(difference, in standard errors, and as a percentage of the absolute Heston $P \to Q$ span). "
          r"$\|\beta_{\mathrm{raw}}\|$ at C0 measures how hard the martingale block alone must work on each prior.",
          "tab:overlay_spread", note=note, star=True, source=src)


# --------------------------------------------------------------------------

EMITTERS = dict(gaussian=gaussian, taskb=taskb, taskc=taskc, amortization=amortization, overlay=overlay)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", nargs="*", choices=sorted(EMITTERS), help="run a subset")
    args = ap.parse_args()
    os.makedirs(TAB, exist_ok=True); os.makedirs(FIG, exist_ok=True)
    for name in (args.only or sorted(EMITTERS)):
        print(f"[{name}]")
        try:
            EMITTERS[name]()
        except Exception as e:                                   # one bad artifact must not stop the rest
            print(f"  FAILED {name}: {type(e).__name__}: {e}")


if __name__ == "__main__":
    main()
